name: daawah_app
description: مشروع تطبيق دعوة.
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # --- Media & UI ---
  better_player_plus: ^1.1.2
  youtube_player_flutter: ^9.0.0
  video_player: ^2.8.1
  chewie: ^1.7.4
  just_audio: ^0.10.5
  audio_session: ^0.1.18
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.0
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.1.0
  convex_bottom_bar: ^3.2.0
  flutter_html: ^3.0.0-beta.2
  nb_utils: ^7.1.8
  cupertino_icons: ^1.0.6

  # --- Functionality ---
  wakelock_plus: ^1.4.0
  share_plus: ^7.2.2
  url_launcher: ^6.3.0
  webview_flutter: ^4.7.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.3

  # --- Firebase & Notifications ---
  firebase_core: ^3.4.1
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^17.2.1
  # (تم حذف timezone من هنا)

  # --- Architecture & Network ---
  flutter_bloc: ^8.1.5
  get_it: ^7.6.0
  injectable: ^2.3.2
  dio: ^5.4.0
  http: ^1.2.1
  rxdart: ^0.27.7
  equatable: ^2.0.5
  stream_transform: ^2.1.0
  intl: ^0.20.2
  html: any
  connectivity_plus: ^7.0.0
  adhan: ^2.0.0+1
  geolocator: ^14.0.2
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

# إعدادات أيقونة التطبيق
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/alogo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    # Media
    - assets/videos/Comp1.mp4
    - assets/images/logo.png
    - assets/images/bbg.jpg
    - assets/images/app_icon1.png
    - assets/images/frame.png
    - assets/images/cover_frame.jpg
    - assets/images/athkar/

    # Icons
    - assets/icons/telegram.png
    - assets/icons/x.png
    - assets/icons/fb.png
    - assets/icons/insta.png
    - assets/icons/tiktok.png
    - assets/icons/youtube.png
    - assets\images\alogo.png




    # Web Files (Privacy Policy etc.)
    - assets/web/aboutus.html
    - assets/web/privacy.html
    - assets/web/terms.html

    # Json Data
    - assets/json/fixed_schedule.json

    # Quran Assets
    - assets/quran/surahs_index.json
    - assets/quran/juzs_index.json
    - assets/quran/mushafs_list.json
    - assets/hisn_full.json

    # Quran Data Folders
    - assets/json/quran_data/
    - assets/json/coords_hafs/
    - assets/json/coords_warsh/
    - assets/json/coords_kalon/
    - assets/json/coords_dory/
    - assets/json/hafs/
    - assets/json/athkar/morning.json        # <--- 🔥 أضف هذا السطر الجديد
    - assets/json/athkar/evening.json